application: zeebo-devel
version: 1
runtime: python
api_version: 1

handlers:
- url: /main.css
  static_files: site/main.css
  upload: site/main.css
- url: /_wave/.*
  script: sa-auto-adder.py
- url: /assets
  static_dir: /assets
- url: /.*
  script: site/main.py
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?README$  